name: wellbeings
description: A new Flutter project.
publish_to: 'none'

version: 1.0.13+13

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  sign_in_with_apple: ^7.0.1
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.1.0
  cloud_firestore: ^6.0.1
  cupertino_icons: ^1.0.2
  dash_chat_2: ^0.0.19
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  flutter_tts: ^4.2.0
  avatar_glow: ^3.0.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.7.0
  firebase_analytics: ^12.0.1
  percent_indicator: ^4.2.3
  sms_autofill: ^2.4.1
  flutter_webrtc: ^1.1.0
  googleapis_auth: ^2.0.0
  googleapis: ^14.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^19.3.1
  flutter_staggered_animations: ^1.1.1
  freezed: ^3.0.0-0.0.dev
  freezed_annotation: ^3.1.0
  google_fonts: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.2.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  just_audio: ^0.10.5
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  loader_overlay: ^5.0.0
  lottie: ^3.2.0
  mime: ^2.0.0
  path_provider: ^2.0.14
  permission_handler: ^12.0.1
  rxdart: ^0.28.0
  timeago: ^3.4.0
  camera: ^0.11.1
  firebase_auth: ^6.0.2
  sign_in_button: ^4.0.1
  google_sign_in: ^7.1.1
  camerawesome: ^2.1.0
  file_picker: ^10.3.2
  subtitle_wrapper_package: ^2.2.0
  chewie: ^1.7.5
  ansi_styles: ^0.3.2+1
  country_code_picker: ^3.0.0
  flutter_spinkit: ^5.2.0
  speech_to_text: ^7.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

# Move this section to root level (not under dev_dependencies)
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.20

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/service_account/wellbeing-b147a-firebase-adminsdk-7z0wu-d03701c72e.json